apiVersion: apps/v1
kind: Deployment
metadata:
  name: corporate-website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corporate-website
  template:
    metadata:
      labels:
        app: corporate-website
    spec:
      containers:
      - name: corporate-website
        image: kasthurirejith213/corporate-website:v1
        ports:
        - containerPort: 80